# Uncomment this line to define a global platform for your project
# platform :ios, '10.0'

# Uncomment this line if you're using Swift
use_frameworks!

workspace 'iOS-Verification-SDK'
project 'VerificationSample/VerificationSample.xcodeproj'

target 'VerificationSample' do
  project 'VerificationSample/VerificationSample.xcodeproj'
  pod 'SinchVerificationSDK', '~> 3.2.0'
end
